
import requests

def get_emoji():
	url="https://www.unicode.org/Public/13.0.0/ucd/emoji/emoji-data.txt"
	unicode_file_string = requests.get(url).text
	unicode_em_1 = {}
	# s = s.split('\n')
	for line in unicode_file_string.split('\n'):
	    if line and not line.startswith('#'):
	        # unicode_em_1[line.split(';')[0].strip().lower()] = ''.join(line.split(')')[1:]).strip()
	        unicode_em_1[line.split('(')[1].split(')')[0]] = ''.join(line.split(')')[1:]).strip()

	for key in list(unicode_em_1.keys()):
	    if '..' in key:
	        unicode_em_1[key.split('..')[0]] = unicode_em_1[key].split('..')[0]
	        unicode_em_1[key.split('..')[1]] = unicode_em_1[key].split('..')[1]
	        del unicode_em_1[key]

	for k,v in unicode_em_1.items():
	    unicode_em_1[k]='<'+v+'>'


	unicode_em_2 = {
		"😀" : "<grinning>" ,
		"😃" : "<smiley>" ,
		"😄" : "<smile>" ,
		"😁" : "<grin>" ,
		"😆" : "<laughing>", 
		"😅" : "<sweat smile>" ,
		"😂" : "<joy>" ,
		"🤣" : "<rofl>" ,
		"☺️" : "<relaxed>" ,
		"😊" : "<blush>" ,
		"😇" : "<innocent>" ,
		"🙂" : "<slightly smiling face>" ,
		"🙃" : "<upside down face>" ,
		"😉" : "<wink>" ,
		"😌" : "<relieved>" ,
		"😍" : "<heart eyes>" ,
		"😘" : "<kissing heart>" ,
		"😗" : "<kissing>" ,
		"😙" : "<kissing smiling eyes>" ,
		"😚" : "<kissing closed eyes>" ,
		"😋" : "<yum>" ,
		"😜" : "<stuck out tongue winking eye>" ,
		"😝" : "<stuck out tongue closed eyes>" ,
		"😛" : "<stuck out tongue>" ,
		"🤑" : "<money mouth face>" ,
		"🤗" : "<hugs>" ,
		"🤓" : "<nerd face>" ,
		"😎" : "<sunglasses>" ,
		"🤡" : "<clown face>" ,
		"🤠" : "<cowboy hat face>" ,
		"😏" : "<smirk>" ,
		"😒" : "<unamused>" ,
		"😞" : "<disappointed>" ,
		"😔" : "<pensive>" ,
		"😟" : "<worried>" ,
		"😕" : "<confused>" ,
		"🙁" : "<slightly frowning face>" ,
		"☹️" : "<frowning face>" ,
		"😣" : "<persevere>" ,
		"😖" : "<confounded>" ,
		"😫" : "<tired face>" ,
		"😩" : "<weary>" ,
		"😤" : "<triumph>" ,
		"😠" : "<angry>" ,
		"😡" : "<rage>", 
		"😶" : "<no mouth>" ,
		"😐" : "<neutral face>" ,
		"😑" : "<expressionless>" ,
		"😯" : "<hushed>" ,
		"😦" : "<frowning>" ,
		"😧" : "<anguished>" ,
		"😮" : "<open mouth>" ,
		"😲" : "<astonished>" ,
		"😵" : "<dizzy face>" ,
		"😳" : "<flushed>" ,
		"😱" : "<scream>" ,
		"😨" : "<fearful>" ,
		"😰" : "<cold sweat>" ,
		"😢" : "<cry>" ,
		"😥" : "<disappointed relieved>" ,
		"🤤" : "<drooling face>" ,
		"😭" : "<sob>" ,
		"😓" : "<sweat>" ,
		"😪" : "<sleepy>" ,
		"😴" : "<sleeping>" ,
		"🙄" : "<roll eyes>" ,
		"🤔" : "<thinking>" ,
		"🤥" : "<lying face>" ,
		"😬" : "<grimacing>" ,
		"🤐" : "<zipper mouth face>" ,
		"🤢" : "<nauseated face>" ,
		"🤧" : "<sneezing face>" ,
		"😷" : "<mask>" ,
		"🤒" : "<face with thermometer>" ,
		"🤕" : "<face with head bandage>" ,
		"😈" : "<smiling imp>" ,
		"👿" : "<imp>" ,
		"👹" : "<japanese ogre>" ,
		"👺" : "<japanese goblin>" ,
		"💩" : "<hankey>", 
		"👻" : "<ghost>" ,
		"💀" : "<skull>" ,
		"☠️" : "<skull and crossbones>" ,
		"👽" : "<alien>" ,
		"👾" : "<space invader>" ,
		"🤖" : "<robot>" ,
		"🎃" : "<jack o lantern>" ,
		"😺" : "<smiley cat>" ,
		"😸" : "<smile cat>" ,
		"😹" : "<joy cat>" ,
		"😻" : "<heart eyes cat>" ,
		"😼" : "<smirk cat>" ,
		"😽" : "<kissing cat>" ,
		"🙀" : "<scream cat>" ,
		"😿" : "<crying cat face>" ,
		"😾" : "<pouting cat>" ,
		"👐" : "<open hands>" ,
		"🙌" : "<raised hands>" ,
		"👏" : "<clap>" ,
		"🙏" : "<pray>" ,
		"🤝" : "<handshake>" ,
		"👍" : "<+1>", 
		"👎" : "<-1>", 
		"👊" : "<fist oncoming>", 
		"✊" : "<fist raised>", 
		"🤛" : "<fist left>" ,
		"🤜" : "<fist right>" ,
		"🤞" : "<crossed fingers>" ,
		"✌️" : "<v>" ,
		"🤘" : "<metal>" ,
		"👌" : "<ok hand>" ,
		"👈" : "<point left>" ,
		"👉" : "<point right>" ,
		"👆" : "<point up 2>" ,
		"👇" : "<point down>" ,
		"☝️" : "<point up>" ,
		"✋" : "<hand>", 
		"🤚" : "<raised back of hand>" ,
		"🖐" : "<raised hand with fingers splayed>" ,
		"🖖" : "<vulcan salute>" ,
		"👋" : "<wave>" ,
		"🤙" : "<call me hand>" ,
		"💪" : "<muscle>" ,
		"🖕" : "<middle finger>", 
		"✍️" : "<writing hand>" ,
		"🤳" : "<selfie>" ,
		"💅" : "<nail care>" ,
		"💍" : "<ring>" ,
		"💄" : "<lipstick>" ,
		"💋" : "<kiss>" ,
		"👄" : "<lips>" ,
		"👅" : "<tongue>" ,
		"👂" : "<ear>" ,
		"👃" : "<nose>" ,
		"👣" : "<footprints>" ,
		"👁" : "<eye>" ,
		"👀" : "<eyes>" ,
		"🗣" : "<speaking head>" ,
		"👤" : "<bust in silhouette>" ,
		"👥" : "<busts in silhouette>" ,
		"👶" : "<baby>" ,
		"👦" : "<boy>" ,
		"👧" : "<girl>" ,
		"👨" : "<man>" ,
		"👩" : "<woman>" ,
		"👱‍♀" : "<blonde woman>" ,
		"👱" : "<blonde man>", 
		"👴" : "<older man>" ,
		"👵" : "<older woman>" ,
		"👲" : "<man with gua pi mao>" ,
		"👳‍♀" : "<woman with turban>" ,
		"👳" : "<man with turban>" ,
		"👮‍♀" : "<policewoman>" ,
		"👮" : "<policeman>", 
		"👷‍♀" : "<construction worker woman>" ,
		"👷" : "<construction worker man>", 
		"💂‍♀" : "<guardswoman>" ,
		"💂" : "<guardsman>" ,
		"🕵️‍♀️" : "<female detective>" ,
		"🕵" : "<male detective>", 
		"👩‍⚕" : "<woman health worker>" ,
		"👨‍⚕" : "<man health worker>" ,
		"👩‍🌾" : "<woman farmer>" ,
		"👨‍🌾" : "<man farmer>" ,
		"👩‍🍳" : "<woman cook>" ,
		"👨‍🍳" : "<man cook>" ,
		"👩‍🎓" : "<woman student>" ,
		"👨‍🎓" : "<man student>" ,
		"👩‍🎤" : "<woman singer>" ,
		"👨‍🎤" : "<man singer>" ,
		"👩‍🏫" : "<woman teacher>" ,
		"👨‍🏫" : "<man teacher>" ,
		"👩‍🏭" : "<woman factory worker>" ,
		"👨‍🏭" : "<man factory worker>" ,
		"👩‍💻" : "<woman technologist>" ,
		"👨‍💻" : "<man technologist>" ,
		"👩‍💼" : "<woman office worker>" ,
		"👨‍💼" : "<man office worker>" ,
		"👩‍🔧" : "<woman mechanic>" ,
		"👨‍🔧" : "<man mechanic>" ,
		"👩‍🔬" : "<woman scientist>" ,
		"👨‍🔬" : "<man scientist>" ,
		"👩‍🎨" : "<woman artist>" ,
		"👨‍🎨" : "<man artist>" ,
		"👩‍🚒" : "<woman firefighter>" ,
		"👨‍🚒" : "<man firefighter>" ,
		"👩‍✈" : "<woman pilot>" ,
		"👨‍✈" : "<man pilot>" ,
		"👩‍🚀" : "<woman astronaut>" ,
		"👨‍🚀" : "<man astronaut>" ,
		"👩‍⚖" : "<woman judge>" ,
		"👨‍⚖" : "<man judge>" ,
		"🤶" : "<mrs claus>" ,
		"🎅" : "<santa>" ,
		"👸" : "<princess>" ,
		"🤴" : "<prince>" ,
		"👰" : "<bride with veil>" ,
		"🤵" : "<man in tuxedo>" ,
		"👼" : "<angel>" ,
		"🤰" : "<pregnant woman>" ,
		"🙇‍♀" : "<bowing woman>" ,
		"🙇" : "<bowing man>", 
		"💁" : "<tipping hand woman>", 
		"💁‍♂" : "<tipping hand man>", 
		"🙅" : "<no good woman>", 
		"🙅‍♂" : "<no good man>", 
		"🙆" : "<ok woman>" ,
		"🙆‍♂" : "<ok man>" ,
		"🙋" : "<raising hand woman>", 
		"🙋‍♂" : "<raising hand man>" ,
		"🤦‍♀" : "<woman facepalming>" ,
		"🤦‍♂" : "<man facepalming>" ,
		"🤷‍♀" : "<woman shrugging>" ,
		"🤷‍♂" : "<man shrugging>" ,
		"🙎" : "<pouting woman>", 
		"🙎‍♂" : "<pouting man>" ,
		"🙍" : "<frowning woman>", 
		"🙍‍♂" : "<frowning man>" ,
		"💇" : "<haircut woman>", 
		"💇‍♂" : "<haircut man>" ,
		"💆" : "<massage woman>", 
		"💆‍♂" : "<massage man>" ,
		"🕴" : "<business suit levitating>" ,
		"💃" : "<dancer>" ,
		"🕺" : "<man dancing>" ,
		"👯" : "<dancing women>", 
		"👯‍♂" : "<dancing men>" ,
		"🚶‍♀" : "<walking woman>" ,
		"🚶" : "<walking man>", 
		"🏃‍♀" : "<running woman>" ,
		"🏃" : "<running man>", 
		"👫" : "<couple>" ,
		"👭" : "<two women holding hands>" ,
		"👬" : "<two men holding hands>" ,
		"💑" : "<couple with heart woman man>", 
		"👩‍❤️‍👩" : "<couple with heart woman woman>" ,
		"👨‍❤️‍👨" : "<couple with heart man man>" ,
		"💏" : "<couplekiss man woman>" ,
		"👩‍❤️‍💋‍👩" : "<couplekiss woman woman>" ,
		"👨‍❤️‍💋‍👨" : "<couplekiss man man>" ,
		"👪" : "<family man woman boy>", 
		"👨‍👩‍👧" : "<family man woman girl>" ,
		"👨‍👩‍👧‍👦" : "<family man woman girl boy>" ,
		"👨‍👩‍👦‍👦" : "<family man woman boy boy>" ,
		"👨‍👩‍👧‍👧" : "<family man woman girl girl>" ,
		"👩‍👩‍👦" : "<family woman woman boy>" ,
		"👩‍👩‍👧" : "<family woman woman girl>" ,
		"👩‍👩‍👧‍👦" : "<family woman woman girl boy>" ,
		"👩‍👩‍👦‍👦" : "<family woman woman boy boy>" ,
		"👩‍👩‍👧‍👧" : "<family woman woman girl girl>" ,
		"👨‍👨‍👦" : "<family man man boy>" ,
		"👨‍👨‍👧" : "<family man man girl>" ,
		"👨‍👨‍👧‍👦" : "<family man man girl boy>" ,
		"👨‍👨‍👦‍👦" : "<family man man boy boy>" ,
		"👨‍👨‍👧‍👧" : "<family man man girl girl>" ,
		"👩‍👦" : "<family woman boy>" ,
		"👩‍👧" : "<family woman girl>" ,
		"👩‍👧‍👦" : "<family woman girl boy>" ,
		"👩‍👦‍👦" : "<family woman boy boy>" ,
		"👩‍👧‍👧" : "<family woman girl girl>" ,
		"👨‍👦" : "<family man boy>" ,
		"👨‍👧" : "<family man girl>" ,
		"👨‍👧‍👦" : "<family man girl boy>" ,
		"👨‍👦‍👦" : "<family man boy boy>" ,
		"👨‍👧‍👧" : "<family man girl girl>" ,
		"👚" : "<womans clothes>" ,
		"👕" : "<shirt>", 
		"👖" : "<jeans>" ,
		"👔" : "<necktie>" ,
		"👗" : "<dress>" ,
		"👙" : "<bikini>" ,
		"👘" : "<kimono>" ,
		"👠" : "<high heel>" ,
		"👡" : "<sandal>" ,
		"👢" : "<boot>" ,
		"👞" : "<mans shoe>", 
		"👟" : "<athletic shoe>" ,
		"👒" : "<womans hat>" ,
		"🎩" : "<tophat>" ,
		"🎓" : "<mortar board>" ,
		"👑" : "<crown>" ,
		"⛑" : "<rescue worker helmet>" ,
		"🎒" : "<school satchel>" ,
		"👝" : "<pouch>" ,
		"👛" : "<purse>" ,
		"👜" : "<handbag>" ,
		"💼" : "<briefcase>" ,
		"👓" : "<eyeglasses>" ,
		"🕶" : "<dark sunglasses>" ,
		"🌂" : "<closed umbrella>" ,
		"☂️" : "<open umbrella>" ,
		"🐶" : "<dog>" ,
		"🐱" : "<cat>" ,
		"🐭" : "<mouse>" ,
		"🐹" : "<hamster>" ,
		"🐰" : "<rabbit>" ,
		"🦊" : "<fox face>" ,
		"🐻" : "<bear>" ,
		"🐼" : "<panda face>" ,
		"🐨" : "<koala>" ,
		"🐯" : "<tiger>" ,
		"🦁" : "<lion>" ,
		"🐮" : "<cow>" ,
		"🐷" : "<pig>" ,
		"🐽" : "<pig nose>" ,
		"🐸" : "<frog>" ,
		"🐵" : "<monkey face>" ,
		"🙈" : "<see no evil>" ,
		"🙉" : "<hear no evil>" ,
		"🙊" : "<speak no evil>" ,
		"🐒" : "<monkey>" ,
		"🐔" : "<chicken>" ,
		"🐧" : "<penguin>" ,
		"🐦" : "<bird>" ,
		"🐤" : "<baby chick>" ,
		"🐣" : "<hatching chick>" ,
		"🐥" : "<hatched chick>" ,
		"🦆" : "<duck>" ,
		"🦅" : "<eagle>" ,
		"🦉" : "<owl>" ,
		"🦇" : "<bat>" ,
		"🐺" : "<wolf>" ,
		"🐗" : "<boar>" ,
		"🐴" : "<horse>" ,
		"🦄" : "<unicorn>" ,
		"🐝" : "<bee>", 
		"🐛" : "<bug>" ,
		"🦋" : "<butterfly>" ,
		"🐌" : "<snail>" ,
		"🐚" : "<shell>" ,
		"🐞" : "<beetle>" ,
		"🐜" : "<ant>" ,
		"🕷" : "<spider>" ,
		"🕸" : "<spider web>" ,
		"🐢" : "<turtle>" ,
		"🐍" : "<snake>" ,
		"🦎" : "<lizard>" ,
		"🦂" : "<scorpion>" ,
		"🦀" : "<crab>" ,
		"🦑" : "<squid>" ,
		"🐙" : "<octopus>" ,
		"🦐" : "<shrimp>" ,
		"🐠" : "<tropical fish>" ,
		"🐟" : "<fish>" ,
		"🐡" : "<blowfish>" ,
		"🐬" : "<dolphin>", 
		"🦈" : "<shark>" ,
		"🐳" : "<whale>" ,
		"🐋" : "<whale2>" ,
		"🐊" : "<crocodile>" ,
		"🐆" : "<leopard>" ,
		"🐅" : "<tiger2>" ,
		"🐃" : "<water buffalo>" ,
		"🐂" : "<ox>" ,
		"🐄" : "<cow2>" ,
		"🦌" : "<deer>" ,
		"🐪" : "<dromedary camel>" ,
		"🐫" : "<camel>" ,
		"🐘" : "<elephant>" ,
		"🦏" : "<rhinoceros>" ,
		"🦍" : "<gorilla>" ,
		"🐎" : "<racehorse>" ,
		"🐖" : "<pig2>" ,
		"🐐" : "<goat>" ,
		"🐏" : "<ram>" ,
		"🐑" : "<sheep>" ,
		"🐕" : "<dog2>" ,
		"🐩" : "<poodle>" ,
		"🐈" : "<cat2>" ,
		"🐓" : "<rooster>" ,
		"🦃" : "<turkey>" ,
		"🕊" : "<dove>" ,
		"🐇" : "<rabbit2>" ,
		"🐁" : "<mouse2>" ,
		"🐀" : "<rat>" ,
		"🐿" : "<chipmunk>" ,
		"🐾" : "<feet>", 
		"🐉" : "<dragon>" ,
		"🐲" : "<dragon face>" ,
		"🌵" : "<cactus>" ,
		"🎄" : "<christmas tree>" ,
		"🌲" : "<evergreen tree>" ,
		"🌳" : "<deciduous tree>" ,
		"🌴" : "<palm tree>" ,
		"🌱" : "<seedling>" ,
		"🌿" : "<herb>" ,
		"☘️" : "<shamrock>" ,
		"🍀" : "<four leaf clover>" ,
		"🎍" : "<bamboo>" ,
		"🎋" : "<tanabata tree>" ,
		"🍃" : "<leaves>" ,
		"🍂" : "<fallen leaf>" ,
		"🍁" : "<maple leaf>" ,
		"🍄" : "<mushroom>" ,
		"🌾" : "<ear of rice>" ,
		"💐" : "<bouquet>" ,
		"🌷" : "<tulip>" ,
		"🌹" : "<rose>" ,
		"🥀" : "<wilted flower>" ,
		"🌻" : "<sunflower>" ,
		"🌼" : "<blossom>" ,
		"🌸" : "<cherry blossom>" ,
		"🌺" : "<hibiscus>" ,
		"🌎" : "<earth americas>" ,
		"🌍" : "<earth africa>" ,
		"🌏" : "<earth asia>" ,
		"🌕" : "<full moon>" ,
		"🌖" : "<waning gibbous moon>" ,
		"🌗" : "<last quarter moon>" ,
		"🌘" : "<waning crescent moon>" ,
		"🌑" : "<new moon>" ,
		"🌒" : "<waxing crescent moon>" ,
		"🌓" : "<first quarter moon>" ,
		"🌔" : "<moon>", 
		"🌚" : "<new moon with face>" ,
		"🌝" : "<full moon with face>" ,
		"🌞" : "<sun with face>" ,
		"🌛" : "<first quarter moon with face>" ,
		"🌜" : "<last quarter moon with face>" ,
		"🌙" : "<crescent moon>" ,
		"💫" : "<dizzy>" ,
		"⭐️" : "<star>" ,
		"🌟" : "<star2>" ,
		"✨" : "<sparkles>" ,
		"⚡️" : "<zap>" ,
		"🔥" : "<fire>" ,
		"💥" : "<boom>", 
		"☄" : "<comet>" ,
		"☀️" : "<sunny>" ,
		"🌤" : "<sun behind small cloud>" ,
		"⛅️" : "<partly sunny>" ,
		"🌥" : "<sun behind large cloud>" ,
		"🌦" : "<sun behind rain cloud>" ,
		"🌈" : "<rainbow>" ,
		"☁️" : "<cloud>" ,
		"🌧" : "<cloud with rain>" ,
		"⛈" : "<cloud with lightning and rain>" ,
		"🌩" : "<cloud with lightning>" ,
		"🌨" : "<cloud with snow>" ,
		"☃️" : "<snowman with snow>" ,
		"⛄️" : "<snowman>" ,
		"❄️" : "<snowflake>" ,
		"🌬" : "<wind face>" ,
		"💨" : "<dash>" ,
		"🌪" : "<tornado>" ,
		"🌫" : "<fog>" ,
		"🌊" : "<ocean>" ,
		"💧" : "<droplet>" ,
		"💦" : "<sweat drops>" ,
		"☔️" : "<umbrella>" ,
		"🍏" : "<green apple>" ,
		"🍎" : "<apple>" ,
		"🍐" : "<pear>" ,
		"🍊" : "<tangerine>", 
		"🍋" : "<lemon>" ,
		"🍌" : "<banana>" ,
		"🍉" : "<watermelon>" ,
		"🍇" : "<grapes>" ,
		"🍓" : "<strawberry>" ,
		"🍈" : "<melon>" ,
		"🍒" : "<cherries>" ,
		"🍑" : "<peach>" ,
		"🍍" : "<pineapple>" ,
		"🥝" : "<kiwi fruit>" ,
		"🥑" : "<avocado>" ,
		"🍅" : "<tomato>" ,
		"🍆" : "<eggplant>" ,
		"🥒" : "<cucumber>" ,
		"🥕" : "<carrot>" ,
		"🌽" : "<corn>" ,
		"🌶" : "<hot pepper>" ,
		"🥔" : "<potato>" ,
		"🍠" : "<sweet potato>" ,
		"🌰" : "<chestnut>" ,
		"🥜" : "<peanuts>" ,
		"🍯" : "<honey pot>" ,
		"🥐" : "<croissant>" ,
		"🍞" : "<bread>" ,
		"🥖" : "<baguette bread>" ,
		"🧀" : "<cheese>" ,
		"🥚" : "<egg>" ,
		"🍳" : "<fried egg>" ,
		"🥓" : "<bacon>" ,
		"🥞" : "<pancakes>" ,
		"🍤" : "<fried shrimp>" ,
		"🍗" : "<poultry leg>" ,
		"🍖" : "<meat on bone>" ,
		"🍕" : "<pizza>" ,
		"🌭" : "<hotdog>" ,
		"🍔" : "<hamburger>" ,
		"🍟" : "<fries>" ,
		"🥙" : "<stuffed flatbread>" ,
		"🌮" : "<taco>" ,
		"🌯" : "<burrito>" ,
		"🥗" : "<green salad>" ,
		"🥘" : "<shallow pan of food>" ,
		"🍝" : "<spaghetti>" ,
		"🍜" : "<ramen>" ,
		"🍲" : "<stew>" ,
		"🍥" : "<fish cake>" ,
		"🍣" : "<sushi>" ,
		"🍱" : "<bento>" ,
		"🍛" : "<curry>" ,
		"🍚" : "<rice>" ,
		"🍙" : "<rice ball>" ,
		"🍘" : "<rice cracker>" ,
		"🍢" : "<oden>" ,
		"🍡" : "<dango>" ,
		"🍧" : "<shaved ice>" ,
		"🍨" : "<ice cream>" ,
		"🍦" : "<icecream>" ,
		"🍰" : "<cake>" ,
		"🎂" : "<birthday>" ,
		"🍮" : "<custard>" ,
		"🍭" : "<lollipop>" ,
		"🍬" : "<candy>" ,
		"🍫" : "<chocolate bar>" ,
		"🍿" : "<popcorn>" ,
		"🍩" : "<doughnut>" ,
		"🍪" : "<cookie>" ,
		"🥛" : "<milk glass>" ,
		"🍼" : "<baby bottle>" ,
		"☕️" : "<coffee>" ,
		"🍵" : "<tea>" ,
		"🍶" : "<sake>" ,
		"🍺" : "<beer>" ,
		"🍻" : "<beers>" ,
		"🥂" : "<clinking glasses>" ,
		"🍷" : "<wine glass>" ,
		"🥃" : "<tumbler glass>" ,
		"🍸" : "<cocktail>" ,
		"🍹" : "<tropical drink>" ,
		"🍾" : "<champagne>" ,
		"🥄" : "<spoon>" ,
		"🍴" : "<fork and knife>" ,
		"🍽" : "<plate with cutlery>" ,
		"⚽️" : "<soccer>" ,
		"🏀" : "<basketball>" ,
		"🏈" : "<football>" ,
		"⚾️" : "<baseball>" ,
		"🎾" : "<tennis>" ,
		"🏐" : "<volleyball>" ,
		"🏉" : "<rugby football>" ,
		"🎱" : "<8ball>" ,
		"🏓" : "<ping pong>" ,
		"🏸" : "<badminton>" ,
		"🥅" : "<goal net>" ,
		"🏒" : "<ice hockey>" ,
		"🏑" : "<field hockey>" ,
		"🏏" : "<cricket>" ,
		"⛳️" : "<golf>" ,
		"🏹" : "<bow and arrow>" ,
		"🎣" : "<fishing pole and fish>" ,
		"🥊" : "<boxing glove>" ,
		"🥋" : "<martial arts uniform>" ,
		"⛸" : "<ice skate>" ,
		"🎿" : "<ski>" ,
		"⛷" : "<skier>" ,
		"🏂" : "<snowboarder>" ,
		"🏋️‍♀️" : "<weight lifting woman>" ,
		"🏋" : "<weight lifting man>" ,
		"🤺" : "<person fencing>" ,
		"🤼‍♀" : "<women wrestling>" ,
		"🤼‍♂" : "<men wrestling>" ,
		"🤸‍♀" : "<woman cartwheeling>" ,
		"🤸‍♂" : "<man cartwheeling>" ,
		"⛹️‍♀️" : "<basketball woman>" ,
		"⛹" : "<basketball man>" ,
		"🤾‍♀" : "<woman playing handball>" ,
		"🤾‍♂" : "<man playing handball>" ,
		"🏌️‍♀️" : "<golfing woman>" ,
		"🏌" : "<golfing man>" ,
		"🏄‍♀" : "<surfing woman>" ,
		"🏄" : "<surfing man>", 
		"🏊‍♀" : "<swimming woman>" ,
		"🏊" : "<swimming man>", 
		"🤽‍♀" : "<woman playing water polo>" ,
		"🤽‍♂" : "<man playing water polo>" ,
		"🚣‍♀" : "<rowing woman>" ,
		"🚣" : "<rowing man>", 
		"🏇" : "<horse racing>" ,
		"🚴‍♀" : "<biking woman>" ,
		"🚴" : "<biking man>", 
		"🚵‍♀" : "<mountain biking woman>" ,
		"🚵" : "<mountain biking man>", 
		"🎽" : "<running shirt with sash>" ,
		"🏅" : "<medal sports>" ,
		"🎖" : "<medal military>" ,
		"🥇" : "<1st place medal>" ,
		"🥈" : "<2nd place medal>" ,
		"🥉" : "<3rd place medal>" ,
		"🏆" : "<trophy>" ,
		"🏵" : "<rosette>" ,
		"🎗" : "<reminder ribbon>" ,
		"🎫" : "<ticket>" ,
		"🎟" : "<tickets>" ,
		"🎪" : "<circus tent>" ,
		"🤹‍♀" : "<woman juggling>" ,
		"🤹‍♂" : "<man juggling>" ,
		"🎭" : "<performing arts>" ,
		"🎨" : "<art>" ,
		"🎬" : "<clapper>" ,
		"🎤" : "<microphone>" ,
		"🎧" : "<headphones>" ,
		"🎼" : "<musical score>" ,
		"🎹" : "<musical keyboard>" ,
		"🥁" : "<drum>" ,
		"🎷" : "<saxophone>" ,
		"🎺" : "<trumpet>" ,
		"🎸" : "<guitar>" ,
		"🎻" : "<violin>" ,
		"🎲" : "<game die>" ,
		"🎯" : "<dart>" ,
		"🎳" : "<bowling>" ,
		"🎮" : "<video game>" ,
		"🎰" : "<slot machine>" ,
		"🚗" : "<car>", 
		"🚕" : "<taxi>" ,
		"🚙" : "<blue car>" ,
		"🚌" : "<bus>" ,
		"🚎" : "<trolleybus>" ,
		"🏎" : "<racing car>" ,
		"🚓" : "<police car>" ,
		"🚑" : "<ambulance>" ,
		"🚒" : "<fire engine>" ,
		"🚐" : "<minibus>" ,
		"🚚" : "<truck>" ,
		"🚛" : "<articulated lorry>" ,
		"🚜" : "<tractor>" ,
		"🛴" : "<kick scooter>" ,
		"🚲" : "<bike>" ,
		"🛵" : "<motor scooter>" ,
		"🏍" : "<motorcycle>" ,
		"🚨" : "<rotating light>" ,
		"🚔" : "<oncoming police car>" ,
		"🚍" : "<oncoming bus>" ,
		"🚘" : "<oncoming automobile>" ,
		"🚖" : "<oncoming taxi>" ,
		"🚡" : "<aerial tramway>" ,
		"🚠" : "<mountain cableway>" ,
		"🚟" : "<suspension railway>" ,
		"🚃" : "<railway car>" ,
		"🚋" : "<train>" ,
		"🚞" : "<mountain railway>" ,
		"🚝" : "<monorail>" ,
		"🚄" : "<bullettrain side>" ,
		"🚅" : "<bullettrain front>" ,
		"🚈" : "<light rail>" ,
		"🚂" : "<steam locomotive>" ,
		"🚆" : "<train2>" ,
		"🚇" : "<metro>" ,
		"🚊" : "<tram>" ,
		"🚉" : "<station>" ,
		"🚁" : "<helicopter>" ,
		"🛩" : "<small airplane>" ,
		"✈️" : "<airplane>" ,
		"🛫" : "<flight departure>" ,
		"🛬" : "<flight arrival>" ,
		"🚀" : "<rocket>" ,
		"🛰" : "<artificial satellite>" ,
		"💺" : "<seat>" ,
		"🛶" : "<canoe>" ,
		"⛵️" : "<boat>", 
		"🛥" : "<motor boat>" ,
		"🚤" : "<speedboat>" ,
		"🛳" : "<passenger ship>" ,
		"⛴" : "<ferry>" ,
		"🚢" : "<ship>" ,
		"⚓️" : "<anchor>" ,
		"🚧" : "<construction>" ,
		"⛽️" : "<fuelpump>" ,
		"🚏" : "<busstop>" ,
		"🚦" : "<vertical traffic light>" ,
		"🚥" : "<traffic light>" ,
		"🗺" : "<world map>" ,
		"🗿" : "<moyai>" ,
		"🗽" : "<statue of liberty>" ,
		"⛲️" : "<fountain>" ,
		"🗼" : "<tokyo tower>" ,
		"🏰" : "<european castle>" ,
		"🏯" : "<japanese castle>" ,
		"🏟" : "<stadium>" ,
		"🎡" : "<ferris wheel>" ,
		"🎢" : "<roller coaster>" ,
		"🎠" : "<carousel horse>" ,
		"⛱" : "<parasol on ground>" ,
		"🏖" : "<beach umbrella>" ,
		"🏝" : "<desert island>" ,
		"⛰" : "<mountain>" ,
		"🏔" : "<mountain snow>" ,
		"🗻" : "<mount fuji>" ,
		"🌋" : "<volcano>" ,
		"🏜" : "<desert>" ,
		"🏕" : "<camping>" ,
		"⛺️" : "<tent>" ,
		"🛤" : "<railway track>" ,
		"🛣" : "<motorway>" ,
		"🏗" : "<building construction>" ,
		"🏭" : "<factory>" ,
		"🏠" : "<house>" ,
		"🏡" : "<house with garden>" ,
		"🏘" : "<houses>" ,
		"🏚" : "<derelict house>" ,
		"🏢" : "<office>" ,
		"🏬" : "<department store>" ,
		"🏣" : "<post office>" ,
		"🏤" : "<european post office>" ,
		"🏥" : "<hospital>" ,
		"🏦" : "<bank>" ,
		"🏨" : "<hotel>" ,
		"🏪" : "<convenience store>" ,
		"🏫" : "<school>" ,
		"🏩" : "<love hotel>" ,
		"💒" : "<wedding>" ,
		"🏛" : "<classical building>" ,
		"⛪️" : "<church>" ,
		"🕌" : "<mosque>" ,
		"🕍" : "<synagogue>" ,
		"🕋" : "<kaaba>" ,
		"⛩" : "<shinto shrine>" ,
		"🗾" : "<japan>" ,
		"🎑" : "<rice scene>" ,
		"🏞" : "<national park>" ,
		"🌅" : "<sunrise>" ,
		"🌄" : "<sunrise over mountains>" ,
		"🌠" : "<stars>" ,
		"🎇" : "<sparkler>" ,
		"🎆" : "<fireworks>" ,
		"🌇" : "<city sunrise>" ,
		"🌆" : "<city sunset>" ,
		"🏙" : "<cityscape>" ,
		"🌃" : "<night with stars>" ,
		"🌌" : "<milky way>" ,
		"🌉" : "<bridge at night>" ,
		"🌁" : "<foggy>" ,
		"⌚️" : "<watch>" ,
		"📱" : "<iphone>" ,
		"📲" : "<calling>" ,
		"💻" : "<computer>" ,
		"⌨️" : "<keyboard>" ,
		"🖥" : "<desktop computer>" ,
		"🖨" : "<printer>" ,
		"🖱" : "<computer mouse>" ,
		"🖲" : "<trackball>" ,
		"🕹" : "<joystick>" ,
		"🗜" : "<clamp>" ,
		"💽" : "<minidisc>" ,
		"💾" : "<floppy disk>" ,
		"💿" : "<cd>" ,
		"📀" : "<dvd>" ,
		"📼" : "<vhs>" ,
		"📷" : "<camera>" ,
		"📸" : "<camera flash>" ,
		"📹" : "<video camera>" ,
		"🎥" : "<movie camera>" ,
		"📽" : "<film projector>" ,
		"🎞" : "<film strip>" ,
		"📞" : "<telephone receiver>" ,
		"☎️" : "<phone>", 
		"📟" : "<pager>" ,
		"📠" : "<fax>" ,
		"📺" : "<tv>" ,
		"📻" : "<radio>" ,
		"🎙" : "<studio microphone>" ,
		"🎚" : "<level slider>" ,
		"🎛" : "<control knobs>" ,
		"⏱" : "<stopwatch>" ,
		"⏲" : "<timer clock>" ,
		"⏰" : "<alarm clock>" ,
		"🕰" : "<mantelpiece clock>" ,
		"⌛️" : "<hourglass>" ,
		"⏳" : "<hourglass flowing sand>" ,
		"📡" : "<satellite>" ,
		"🔋" : "<battery>" ,
		"🔌" : "<electric plug>" ,
		"💡" : "<bulb>" ,
		"🔦" : "<flashlight>" ,
		"🕯" : "<candle>" ,
		"🗑" : "<wastebasket>" ,
		"🛢" : "<oil drum>" ,
		"💸" : "<money with wings>" ,
		"💵" : "<dollar>" ,
		"💴" : "<yen>" ,
		"💶" : "<euro>" ,
		"💷" : "<pound>" ,
		"💰" : "<moneybag>" ,
		"💳" : "<credit card>" ,
		"💎" : "<gem>" ,
		"⚖️" : "<balance scale>" ,
		"🔧" : "<wrench>" ,
		"🔨" : "<hammer>" ,
		"⚒" : "<hammer and pick>" ,
		"🛠" : "<hammer and wrench>" ,
		"⛏" : "<pick>" ,
		"🔩" : "<nut and bolt>" ,
		"⚙️" : "<gear>" ,
		"⛓" : "<chains>" ,
		"🔫" : "<gun>" ,
		"💣" : "<bomb>" ,
		"🔪" : "<hocho>", 
		"🗡" : "<dagger>" ,
		"⚔️" : "<crossed swords>" ,
		"🛡" : "<shield>" ,
		"🚬" : "<smoking>" ,
		"⚰️" : "<coffin>" ,
		"⚱️" : "<funeral urn>" ,
		"🏺" : "<amphora>" ,
		"🔮" : "<crystal ball>" ,
		"📿" : "<prayer beads>" ,
		"💈" : "<barber>" ,
		"⚗️" : "<alembic>" ,
		"🔭" : "<telescope>" ,
		"🔬" : "<microscope>" ,
		"🕳" : "<hole>" ,
		"💊" : "<pill>" ,
		"💉" : "<syringe>" ,
		"🌡" : "<thermometer>" ,
		"🚽" : "<toilet>" ,
		"🚰" : "<potable water>" ,
		"🚿" : "<shower>" ,
		"🛁" : "<bathtub>" ,
		"🛀" : "<bath>" ,
		"🛎" : "<bellhop bell>" ,
		"🔑" : "<key>" ,
		"🗝" : "<old key>" ,
		"🚪" : "<door>" ,
		"🛋" : "<couch and lamp>" ,
		"🛏" : "<bed>" ,
		"🛌" : "<sleeping bed>" ,
		"🖼" : "<framed picture>" ,
		"🛍" : "<shopping>" ,
		"🛒" : "<shopping cart>" ,
		"🎁" : "<gift>" ,
		"🎈" : "<balloon>" ,
		"🎏" : "<flags>" ,
		"🎀" : "<ribbon>" ,
		"🎊" : "<confetti ball>" ,
		"🎉" : "<tada>" ,
		"🎎" : "<dolls>" ,
		"🏮" : "<izakaya lantern>", 
		"🎐" : "<wind chime>" ,
		"✉️" : "<email>", 
		"📩" : "<envelope with arrow>" ,
		"📨" : "<incoming envelope>" ,
		"📧" : "<e>",
		"💌" : "<love letter>" ,
		"📥" : "<inbox tray>" ,
		"📤" : "<outbox tray>" ,
		"📦" : "<package>" ,
		"🏷" : "<label>" ,
		"📪" : "<mailbox closed>" ,
		"📫" : "<mailbox>" ,
		"📬" : "<mailbox with mail>" ,
		"📭" : "<mailbox with no mail>" ,
		"📮" : "<postbox>" ,
		"📯" : "<postal horn>" ,
		"📜" : "<scroll>" ,
		"📃" : "<page with curl>" ,
		"📄" : "<page facing up>" ,
		"📑" : "<bookmark tabs>" ,
		"📊" : "<bar chart>" ,
		"📈" : "<chart with upwards trend>" ,
		"📉" : "<chart with downwards trend>" ,
		"🗒" : "<spiral notepad>" ,
		"🗓" : "<spiral calendar>" ,
		"📆" : "<calendar>" ,
		"📅" : "<date>" ,
		"📇" : "<card index>" ,
		"🗃" : "<card file box>" ,
		"🗳" : "<ballot box>" ,
		"🗄" : "<file cabinet>" ,
		"📋" : "<clipboard>" ,
		"📁" : "<file folder>" ,
		"📂" : "<open file folder>" ,
		"🗂" : "<card index dividers>" ,
		"🗞" : "<newspaper roll>" ,
		"📰" : "<newspaper>" ,
		"📓" : "<notebook>" ,
		"📔" : "<notebook with decorative cover>" ,
		"📒" : "<ledger>" ,
		"📕" : "<closed book>" ,
		"📗" : "<green book>" ,
		"📘" : "<blue book>" ,
		"📙" : "<orange book>" ,
		"📚" : "<books>" ,
		"📖" : "<book>", 
		"🔖" : "<bookmark>" ,
		"🔗" : "<link>" ,
		"📎" : "<paperclip>" ,
		"🖇" : "<paperclips>" ,
		"📐" : "<triangular ruler>" ,
		"📏" : "<straight ruler>" ,
		"📌" : "<pushpin>" ,
		"📍" : "<round pushpin>" ,
		"✂️" : "<scissors>" ,
		"🖊" : "<pen>" ,
		"🖋" : "<fountain pen>" ,
		"✒️" : "<black nib>" ,
		"🖌" : "<paintbrush>" ,
		"🖍" : "<crayon>" ,
		"📝" : "<memo>", 
		"✏️" : "<pencil2>" ,
		"🔍" : "<mag>" ,
		"🔎" : "<mag right>" ,
		"🔏" : "<lock with ink pen>" ,
		"🔐" : "<closed lock with key>" ,
		"🔒" : "<lock>" ,
		"🔓" : "<unlock>" ,
		"❤️" : "<heart>" ,
		"💛" : "<yellow heart>" ,
		"💚" : "<green heart>" ,
		"💙" : "<blue heart>" ,
		"💜" : "<purple heart>" ,
		"🖤" : "<black heart>" ,
		"💔" : "<broken heart>" ,
		"❣️" : "<heavy heart exclamation>" ,
		"💕" : "<two hearts>" ,
		"💞" : "<revolving hearts>" ,
		"💓" : "<heartbeat>" ,
		"💗" : "<heartpulse>" ,
		"💖" : "<sparkling heart>" ,
		"💘" : "<cupid>" ,
		"💝" : "<gift heart>" ,
		"💟" : "<heart decoration>" ,
		"☮️" : "<peace symbol>" ,
		"✝️" : "<latin cross>" ,
		"☪️" : "<star and crescent>" ,
		"🕉" : "<om>" ,
		"☸️" : "<wheel of dharma>" ,
		"✡️" : "<star of david>" ,
		"🔯" : "<six pointed star>" ,
		"🕎" : "<menorah>" ,
		"☯️" : "<yin yang>" ,
		"☦️" : "<orthodox cross>" ,
		"🛐" : "<place of worship>" ,
		"⛎" : "<ophiuchus>" ,
		"♈️" : "<aries>" ,
		"♉️" : "<taurus>" ,
		"♊️" : "<gemini>" ,
		"♋️" : "<cancer>" ,
		"♌️" : "<leo>" ,
		"♍️" : "<virgo>" ,
		"♎️" : "<libra>" ,
		"♏️" : "<scorpius>" ,
		"♐️" : "<sagittarius>" ,
		"♑️" : "<capricorn>" ,
		"♒️" : "<aquarius>" ,
		"♓️" : "<pisces>" ,
		"🆔" : "<id>" ,
		"⚛️" : "<atom symbol>" ,
		"🉑" : "<accept>" ,
		"☢️" : "<radioactive>" ,
		"☣️" : "<biohazard>" ,
		"📴" : "<mobile phone off>" ,
		"📳" : "<vibration mode>" ,
		"🈶" : "<u6709>" ,
		"🈚️" : "<u7121>" ,
		"🈸" : "<u7533>" ,
		"🈺" : "<u55b6>" ,
		"🈷️" : "<u6708>" ,
		"✴️" : "<eight pointed black star>" ,
		"🆚" : "<vs>" ,
		"💮" : "<white flower>" ,
		"🉐" : "<ideograph advantage>" ,
		"㊙️" : "<secret>" ,
		"㊗️" : "<congratulations>" ,
		"🈴" : "<u5408>" ,
		"🈵" : "<u6e80>" ,
		"🈹" : "<u5272>" ,
		"🈲" : "<u7981>" ,
		"🅰️" : "<a>" ,
		"🅱️" : "<b>" ,
		"🆎" : "<ab>" ,
		"🆑" : "<cl>" ,
		"🅾️" : "<o2>" ,
		"🆘" : "<sos>" ,
		"❌" : "<x>" ,
		"⭕️" : "<o>" ,
		"🛑" : "<stop sign>" ,
		"⛔️" : "<no entry>" ,
		"📛" : "<name badge>" ,
		"🚫" : "<no entry sign>" ,
		"💯" : "<100>" ,
		"💢" : "<anger>" ,
		"♨️" : "<hotsprings>" ,
		"🚷" : "<no pedestrians>" ,
		"🚯" : "<do not litter>" ,
		"🚳" : "<no bicycles>" ,
		"🚱" : "<non>",
		"🔞" : "<underage>" ,
		"📵" : "<no mobile phones>" ,
		"🚭" : "<no smoking>" ,
		"❗️" : "<exclamation>", 
		"❕" : "<grey exclamation>" ,
		"❓" : "<question>" ,
		"❔" : "<grey question>" ,
		"‼️" : "<bangbang>" ,
		"⁉️" : "<interrobang>" ,
		"🔅" : "<low brightness>" ,
		"🔆" : "<high brightness>" ,
		"〽️" : "<part alternation mark>" ,
		"⚠️" : "<warning>" ,
		"🚸" : "<children crossing>" ,
		"🔱" : "<trident>" ,
		"⚜️" : "<fleur de lis>" ,
		"🔰" : "<beginner>" ,
		"♻️" : "<recycle>" ,
		"✅" : "<white check mark>" ,
		"🈯️" : "<u6307>" ,
		"💹" : "<chart>" ,
		"❇️" : "<sparkle>" ,
		"✳️" : "<eight spoked asterisk>" ,
		"❎" : "<negative squared cross mark>" ,
		"🌐" : "<globe with meridians>" ,
		"💠" : "<diamond shape with a dot inside>" ,
		"Ⓜ️" : "<m>" ,
		"🌀" : "<cyclone>" ,
		"💤" : "<zzz>" ,
		"🏧" : "<atm>" ,
		"🚾" : "<wc>" ,
		"♿️" : "<wheelchair>" ,
		"🅿️" : "<parking>" ,
		"🈳" : "<u7a7a>" ,
		"🈂️" : "<sa>" ,
		"🛂" : "<passport control>" ,
		"🛃" : "<customs>" ,
		"🛄" : "<baggage claim>" ,
		"🛅" : "<left luggage>" ,
		"🚹" : "<mens>" ,
		"🚺" : "<womens>" ,
		"🚼" : "<baby symbol>" ,
		"🚻" : "<restroom>" ,
		"🚮" : "<put litter in its place>" ,
		"🎦" : "<cinema>" ,
		"📶" : "<signal strength>" ,
		"🈁" : "<koko>" ,
		"🔣" : "<symbols>" ,
		"ℹ️" : "<information source>" ,
		"🔤" : "<abc>" ,
		"🔡" : "<abcd>" ,
		"🔠" : "<capital abcd>" ,
		"🆖" : "<ng>" ,
		"🆗" : "<ok>" ,
		"🆙" : "<up>" ,
		"🆒" : "<cool>" ,
		"🆕" : "<new>" ,
		"🆓" : "<free>" ,
		"0️⃣" : "<zero>" ,
		"1️⃣" : "<one>" ,
		"2️⃣" : "<two>" ,
		"3️⃣" : "<three>" ,
		"4️⃣" : "<four>" ,
		"5️⃣" : "<five>" ,
		"6️⃣" : "<six>" ,
		"7️⃣" : "<seven>" ,
		"8️⃣" : "<eight>" ,
		"9️⃣" : "<nine>" ,
		"🔟" : "<keycap ten>" ,
		"🔢" : "<1234>" ,
		"#️⃣" : "<hash>" ,
		"▶️" : "<arrow forward>" ,
		"⏸" : "<pause button>" ,
		"⏯" : "<play or pause button>" ,
		"⏹" : "<stop button>" ,
		"⏺" : "<record button>" ,
		"⏭" : "<next track button>" ,
		"⏮" : "<previous track button>" ,
		"⏩" : "<fast forward>" ,
		"⏪" : "<rewind>" ,
		"⏫" : "<arrow double up>" ,
		"⏬" : "<arrow double down>" ,
		"◀️" : "<arrow backward>" ,
		"🔼" : "<arrow up small>" ,
		"🔽" : "<arrow down small>" ,
		"➡️" : "<arrow right>" ,
		"⬅️" : "<arrow left>" ,
		"⬆️" : "<arrow up>" ,
		"⬇️" : "<arrow down>" ,
		"↗️" : "<arrow upper right>" ,
		"↘️" : "<arrow lower right>" ,
		"↙️" : "<arrow lower left>" ,
		"↖️" : "<arrow upper left>" ,
		"↕️" : "<arrow up down>" ,
		"↔️" : "<left right arrow>" ,
		"↪️" : "<arrow right hook>" ,
		"↩️" : "<leftwards arrow with hook>" ,
		"⤴️" : "<arrow heading up>" ,
		"⤵️" : "<arrow heading down>" ,
		"🔀" : "<twisted rightwards arrows>" ,
		"🔁" : "<repeat>" ,
		"🔂" : "<repeat one>" ,
		"🔄" : "<arrows counterclockwise>" ,
		"🔃" : "<arrows clockwise>" ,
		"🎵" : "<musical note>" ,
		"🎶" : "<notes>" ,
		"➕" : "<heavy plus sign>" ,
		"➖" : "<heavy minus sign>" ,
		"➗" : "<heavy division sign>" ,
		"✖️" : "<heavy multiplication x>" ,
		"💲" : "<heavy dollar sign>" ,
		"💱" : "<currency exchange>" ,
		"™️" : "<tm>" ,
		"©️" : "<copyright>" ,
		"®️" : "<registered>" ,
		"〰️" : "<wavy dash>" ,
		"➰" : "<curly loop>" ,
		"➿" : "<loop>" ,
		"🔚" : "<end>" ,
		"🔙" : "<back>" ,
		"🔛" : "<on>" ,
		"🔝" : "<top>" ,
		"🔜" : "<soon>" ,
		"✔️" : "<heavy check mark>" ,
		"☑️" : "<ballot box with check>" ,
		"🔘" : "<radio button>" ,
		"⚪️" : "<white circle>" ,
		"⚫️" : "<black circle>" ,
		"🔴" : "<red circle>" ,
		"🔵" : "<large blue circle>" ,
		"🔺" : "<small red triangle>" ,
		"🔻" : "<small red triangle down>" ,
		"🔸" : "<small orange diamond>" ,
		"🔹" : "<small blue diamond>" ,
		"🔶" : "<large orange diamond>" ,
		"🔷" : "<large blue diamond>" ,
		"🔳" : "<white square button>" ,
		"🔲" : "<black square button>" ,
		"▪️" : "<black small square>" ,
		"▫️" : "<white small square>" ,
		"◾️" : "<black medium small square>" ,
		"◽️" : "<white medium small square>" ,
		"◼️" : "<black medium square>" ,
		"◻️" : "<white medium square>" ,
		"⬛️" : "<black large square>" ,
		"⬜️" : "<white large square>" ,
		"🔈" : "<speaker>" ,
		"🔇" : "<mute>" ,
		"🔉" : "<sound>" ,
		"🔊" : "<loud sound>" ,
		"🔔" : "<bell>" ,
		"🔕" : "<no bell>" ,
		"📣" : "<mega>" ,
		"📢" : "<loudspeaker>" ,
		"👁‍🗨" : "<eye speech bubble>" ,
		"💬" : "<speech balloon>" ,
		"💭" : "<thought balloon>" ,
		"🗯" : "<right anger bubble>" ,
		"♠️" : "<spades>" ,
		"♣️" : "<clubs>" ,
		"♥️" : "<hearts>" ,
		"♦️" : "<diamonds>" ,
		"🃏" : "<black joker>" ,
		"🎴" : "<flower playing cards>" ,
		"🀄️" : "<mahjong>" ,
		"🕐" : "<clock1>" ,
		"🕑" : "<clock2>" ,
		"🕒" : "<clock3>" ,
		"🕓" : "<clock4>" ,
		"🕔" : "<clock5>" ,
		"🕕" : "<clock6>" ,
		"🕖" : "<clock7>" ,
		"🕗" : "<clock8>" ,
		"🕘" : "<clock9>" ,
		"🕙" : "<clock10>" ,
		"🕚" : "<clock11>" ,
		"🕛" : "<clock12>" ,
		"🕜" : "<clock130>" ,
		"🕝" : "<clock230>" ,
		"🕞" : "<clock330>" ,
		"🕟" : "<clock430>" ,
		"🕠" : "<clock530>" ,
		"🕡" : "<clock630>" ,
		"🕢" : "<clock730>" ,
		"🕣" : "<clock830>" ,
		"🕤" : "<clock930>" ,
		"🕥" : "<clock1030>" ,
		"🕦" : "<clock1130>" ,
		"🕧" : "<clock1230>" ,
		"🏳️" : "<white flag>" ,
		"🏴" : "<black flag>" ,
		"🏁" : "<checkered flag>" ,
		"🚩" : "<triangular flag on post>" ,
		"🏳️‍🌈" : "<rainbow flag>" ,
		"🇦🇫" : "<afghanistan>" ,
		"🇦🇽" : "<aland islands>" ,
		"🇦🇱" : "<albania>" ,
		"🇩🇿" : "<algeria>" ,
		"🇦🇸" : "<american samoa>" ,
		"🇦🇩" : "<andorra>" ,
		"🇦🇴" : "<angola>" ,
		"🇦🇮" : "<anguilla>" ,
		"🇦🇶" : "<antarctica>" ,
		"🇦🇬" : "<antigua barbuda>" ,
		"🇦🇷" : "<argentina>" ,
		"🇦🇲" : "<armenia>" ,
		"🇦🇼" : "<aruba>" ,
		"🇦🇺" : "<australia>" ,
		"🇦🇹" : "<austria>" ,
		"🇦🇿" : "<azerbaijan>" ,
		"🇧🇸" : "<bahamas>" ,
		"🇧🇭" : "<bahrain>" ,
		"🇧🇩" : "<bangladesh>" ,
		"🇧🇧" : "<barbados>" ,
		"🇧🇾" : "<belarus>" ,
		"🇧🇪" : "<belgium>" ,
		"🇧🇿" : "<belize>" ,
		"🇧🇯" : "<benin>" ,
		"🇧🇲" : "<bermuda>" ,
		"🇧🇹" : "<bhutan>" ,
		"🇧🇴" : "<bolivia>" ,
		"🇧🇶" : "<caribbean netherlands>" ,
		"🇧🇦" : "<bosnia herzegovina>" ,
		"🇧🇼" : "<botswana>" ,
		"🇧🇷" : "<brazil>" ,
		"🇮🇴" : "<british indian ocean territory>" ,
		"🇻🇬" : "<british virgin islands>" ,
		"🇧🇳" : "<brunei>" ,
		"🇧🇬" : "<bulgaria>" ,
		"🇧🇫" : "<burkina faso>" ,
		"🇧🇮" : "<burundi>" ,
		"🇨🇻" : "<cape verde>" ,
		"🇰🇭" : "<cambodia>" ,
		"🇨🇲" : "<cameroon>" ,
		"🇨🇦" : "<canada>" ,
		"🇮🇨" : "<canary islands>" ,
		"🇰🇾" : "<cayman islands>" ,
		"🇨🇫" : "<central african republic>" ,
		"🇹🇩" : "<chad>" ,
		"🇨🇱" : "<chile>" ,
		"🇨🇳" : "<cn>" ,
		"🇨🇽" : "<christmas island>" ,
		"🇨🇨" : "<cocos islands>" ,
		"🇨🇴" : "<colombia>" ,
		"🇰🇲" : "<comoros>" ,
		"🇨🇬" : "<congo brazzaville>" ,
		"🇨🇩" : "<congo kinshasa>" ,
		"🇨🇰" : "<cook islands>" ,
		"🇨🇷" : "<costa rica>" ,
		"🇨🇮" : "<cote divoire>" ,
		"🇭🇷" : "<croatia>" ,
		"🇨🇺" : "<cuba>" ,
		"🇨🇼" : "<curacao>" ,
		"🇨🇾" : "<cyprus>" ,
		"🇨🇿" : "<czech republic>" ,
		"🇩🇰" : "<denmark>" ,
		"🇩🇯" : "<djibouti>" ,
		"🇩🇲" : "<dominica>" ,
		"🇩🇴" : "<dominican republic>" ,
		"🇪🇨" : "<ecuador>" ,
		"🇪🇬" : "<egypt>" ,
		"🇸🇻" : "<el salvador>" ,
		"🇬🇶" : "<equatorial guinea>" ,
		"🇪🇷" : "<eritrea>" ,
		"🇪🇪" : "<estonia>" ,
		"🇪🇹" : "<ethiopia>" ,
		"🇪🇺" : "<eu>", 
		"🇫🇰" : "<falkland islands>" ,
		"🇫🇴" : "<faroe islands>" ,
		"🇫🇯" : "<fiji>" ,
		"🇫🇮" : "<finland>" ,
		"🇫🇷" : "<fr>" ,
		"🇬🇫" : "<french guiana>" ,
		"🇵🇫" : "<french polynesia>" ,
		"🇹🇫" : "<french southern territories>" ,
		"🇬🇦" : "<gabon>" ,
		"🇬🇲" : "<gambia>" ,
		"🇬🇪" : "<georgia>" ,
		"🇩🇪" : "<de>" ,
		"🇬🇭" : "<ghana>" ,
		"🇬🇮" : "<gibraltar>" ,
		"🇬🇷" : "<greece>" ,
		"🇬🇱" : "<greenland>" ,
		"🇬🇩" : "<grenada>" ,
		"🇬🇵" : "<guadeloupe>" ,
		"🇬🇺" : "<guam>" ,
		"🇬🇹" : "<guatemala>" ,
		"🇬🇬" : "<guernsey>" ,
		"🇬🇳" : "<guinea>" ,
		"🇬🇼" : "<guinea bissau>" ,
		"🇬🇾" : "<guyana>" ,
		"🇭🇹" : "<haiti>" ,
		"🇭🇳" : "<honduras>" ,
		"🇭🇰" : "<hong kong>" ,
		"🇭🇺" : "<hungary>" ,
		"🇮🇸" : "<iceland>" ,
		"🇮🇳" : "<india>" ,
		"🇮🇩" : "<indonesia>" ,
		"🇮🇷" : "<iran>" ,
		"🇮🇶" : "<iraq>" ,
		"🇮🇪" : "<ireland>" ,
		"🇮🇲" : "<isle of man>" ,
		"🇮🇱" : "<israel>" ,
		"🇮🇹" : "<it>" ,
		"🇯🇲" : "<jamaica>" ,
		"🇯🇵" : "<jp>" ,
		"🎌" : "<crossed flags>" ,
		"🇯🇪" : "<jersey>" ,
		"🇯🇴" : "<jordan>" ,
		"🇰🇿" : "<kazakhstan>" ,
		"🇰🇪" : "<kenya>" ,
		"🇰🇮" : "<kiribati>" ,
		"🇽🇰" : "<kosovo>" ,
		"🇰🇼" : "<kuwait>" ,
		"🇰🇬" : "<kyrgyzstan>" ,
		"🇱🇦" : "<laos>" ,
		"🇱🇻" : "<latvia>" ,
		"🇱🇧" : "<lebanon>" ,
		"🇱🇸" : "<lesotho>" ,
		"🇱🇷" : "<liberia>" ,
		"🇱🇾" : "<libya>" ,
		"🇱🇮" : "<liechtenstein>" ,
		"🇱🇹" : "<lithuania>" ,
		"🇱🇺" : "<luxembourg>" ,
		"🇲🇴" : "<macau>" ,
		"🇲🇰" : "<macedonia>" ,
		"🇲🇬" : "<madagascar>" ,
		"🇲🇼" : "<malawi>" ,
		"🇲🇾" : "<malaysia>" ,
		"🇲🇻" : "<maldives>" ,
		"🇲🇱" : "<mali>" ,
		"🇲🇹" : "<malta>" ,
		"🇲🇭" : "<marshall islands>" ,
		"🇲🇶" : "<martinique>" ,
		"🇲🇷" : "<mauritania>" ,
		"🇲🇺" : "<mauritius>" ,
		"🇾🇹" : "<mayotte>" ,
		"🇲🇽" : "<mexico>" ,
		"🇫🇲" : "<micronesia>" ,
		"🇲🇩" : "<moldova>" ,
		"🇲🇨" : "<monaco>" ,
		"🇲🇳" : "<mongolia>" ,
		"🇲🇪" : "<montenegro>" ,
		"🇲🇸" : "<montserrat>" ,
		"🇲🇦" : "<morocco>" ,
		"🇲🇿" : "<mozambique>" ,
		"🇲🇲" : "<myanmar>" ,
		"🇳🇦" : "<namibia>" ,
		"🇳🇷" : "<nauru>" ,
		"🇳🇵" : "<nepal>" ,
		"🇳🇱" : "<netherlands>" ,
		"🇳🇨" : "<new caledonia>" ,
		"🇳🇿" : "<new zealand>" ,
		"🇳🇮" : "<nicaragua>" ,
		"🇳🇪" : "<niger>" ,
		"🇳🇬" : "<nigeria>" ,
		"🇳🇺" : "<niue>" ,
		"🇳🇫" : "<norfolk island>" ,
		"🇲🇵" : "<northern mariana islands>" ,
		"🇰🇵" : "<north korea>" ,
		"🇳🇴" : "<norway>" ,
		"🇴🇲" : "<oman>" ,
		"🇵🇰" : "<pakistan>" ,
		"🇵🇼" : "<palau>" ,
		"🇵🇸" : "<palestinian territories>" ,
		"🇵🇦" : "<panama>" ,
		"🇵🇬" : "<papua new guinea>" ,
		"🇵🇾" : "<paraguay>" ,
		"🇵🇪" : "<peru>" ,
		"🇵🇭" : "<philippines>" ,
		"🇵🇳" : "<pitcairn islands>" ,
		"🇵🇱" : "<poland>" ,
		"🇵🇹" : "<portugal>" ,
		"🇵🇷" : "<puerto rico>" ,
		"🇶🇦" : "<qatar>" ,
		"🇷🇪" : "<reunion>" ,
		"🇷🇴" : "<romania>" ,
		"🇷🇺" : "<ru>" ,
		"🇷🇼" : "<rwanda>" ,
		"🇧🇱" : "<st barthelemy>" ,
		"🇸🇭" : "<st helena>" ,
		"🇰🇳" : "<st kitts nevis>" ,
		"🇱🇨" : "<st lucia>" ,
		"🇵🇲" : "<st pierre miquelon>" ,
		"🇻🇨" : "<st vincent grenadines>" ,
		"🇼🇸" : "<samoa>" ,
		"🇸🇲" : "<san marino>" ,
		"🇸🇹" : "<sao tome principe>" ,
		"🇸🇦" : "<saudi arabia>" ,
		"🇸🇳" : "<senegal>" ,
		"🇷🇸" : "<serbia>" ,
		"🇸🇨" : "<seychelles>" ,
		"🇸🇱" : "<sierra leone>" ,
		"🇸🇬" : "<singapore>" ,
		"🇸🇽" : "<sint maarten>" ,
		"🇸🇰" : "<slovakia>" ,
		"🇸🇮" : "<slovenia>" ,
		"🇸🇧" : "<solomon islands>" ,
		"🇸🇴" : "<somalia>" ,
		"🇿🇦" : "<south africa>" ,
		"🇬🇸" : "<south georgia south sandwich islands>" ,
		"🇰🇷" : "<kr>" ,
		"🇸🇸" : "<south sudan>" ,
		"🇪🇸" : "<es>" ,
		"🇱🇰" : "<sri lanka>" ,
		"🇸🇩" : "<sudan>" ,
		"🇸🇷" : "<suriname>" ,
		"🇸🇿" : "<swaziland>" ,
		"🇸🇪" : "<sweden>" ,
		"🇨🇭" : "<switzerland>" ,
		"🇸🇾" : "<syria>" ,
		"🇹🇼" : "<taiwan>" ,
		"🇹🇯" : "<tajikistan>" ,
		"🇹🇿" : "<tanzania>" ,
		"🇹🇭" : "<thailand>" ,
		"🇹🇱" : "<timor leste>" ,
		"🇹🇬" : "<togo>" ,
		"🇹🇰" : "<tokelau>" ,
		"🇹🇴" : "<tonga>" ,
		"🇹🇹" : "<trinidad tobago>" ,
		"🇹🇳" : "<tunisia>" ,
		"🇹🇷" : "<tr>" ,
		"🇹🇲" : "<turkmenistan>" ,
		"🇹🇨" : "<turks caicos islands>" ,
		"🇹🇻" : "<tuvalu>" ,
		"🇺🇬" : "<uganda>" ,
		"🇺🇦" : "<ukraine>" ,
		"🇦🇪" : "<united arab emirates>" ,
		"🇬🇧" : "<gb>" ,
		"🇺🇸" : "<us>" ,
		"🇻🇮" : "<us virgin islands>" ,
		"🇺🇾" : "<uruguay>" ,
		"🇺🇿" : "<uzbekistan>" ,
		"🇻🇺" : "<vanuatu>" ,
		"🇻🇦" : "<vatican city>" ,
		"🇻🇪" : "<venezuela>" ,
		"🇻🇳" : "<vietnam>" ,
		"🇼🇫" : "<wallis futuna>" ,
		"🇪🇭" : "<western sahara>" ,
		"🇾🇪" : "<yemen>" ,
		"🇿🇲" : "<zambia>" ,
		"🇿🇼" : "<zimbabwe>" 
	}


	z = {**unicode_em_2, **unicode_em_1}

	return z